version: '3.3'






services:
  db-search:
    container_name: search-db
    image: postgres:alpine
    restart: always
    networks:
      - botglazboga
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    -
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env.dist"


networks:
  botnet:
    driver: bridge
